import Head from "next/head";
import UserDashboard from "@/components/UserDashboard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sulthan Fathur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <UserDashboard />
    </>
  );
}
